package gui;

// This is a base class that all our other panels inherit from. It provides
// our child classes with:
//  - The `frame` property - a reference to the GUI main frame
//  - The `app` property - a reference to the root of our data structure in the logic package
//  - The `postInit` method, which will run after everything in the panel is initialized
//
// You shouldn't need to modify anything in this file

public class BasePanel extends javax.swing.JPanel {

    protected Frame frame;
    protected logic.App app;

    public void setMainFrame(Frame frame) {
        this.frame = frame;
    }
    
    public void setApp(logic.App app) {
        this.app = app;
    }
    
    public void postInit() {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
