package gui;

import java.lang.*;
import javax.swing.*;
import java.awt.Color;
import logic.*;

public class DayPanel extends BasePanel {

    private int dayIndex;
    private Day day;
    
    public DayPanel(int dayIndex) {
        this.dayIndex = dayIndex;
        initComponents();  
    }

    public void postInit() {
        // Check if we're inserting a new day
        if (dayIndex == -1) {
            return;
        }
        day = app.getDay(dayIndex);
        txtYear.setText(""+day.getYear());
        txtMonth.setText(""+day.getMonth());
        txtDay.setText(""+day.getDay());
        txtHigh.setText(""+day.getHigh());
        txtLow.setText(""+day.getLow());
        cmbSky.setSelectedIndex(day.getSkyIndex());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        txtMonth = new javax.swing.JTextField();
        txtDay = new javax.swing.JTextField();
        txtHigh = new javax.swing.JTextField();
        txtLow = new javax.swing.JTextField();
        cmbSky = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jLabel1.setText("Year:");

        jLabel2.setText("Month:");

        jLabel3.setText("Day:");

        jLabel4.setText("High:");

        jLabel5.setText("Low:");

        jLabel6.setText("Sky:");

        txtYear.setColumns(10);
        txtYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtYearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtYearFocusLost(evt);
            }
        });

        txtMonth.setColumns(10);
        txtMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMonthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMonthFocusLost(evt);
            }
        });

        txtDay.setColumns(10);
        txtDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDayFocusLost(evt);
            }
        });

        txtHigh.setColumns(10);
        txtHigh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHighFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHighFocusLost(evt);
            }
        });

        txtLow.setColumns(10);
        txtLow.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLowFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLowFocusLost(evt);
            }
        });

        cmbSky.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clear", "Mix Sun/Cloud", "Cloud", "Rain" }));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtYear))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbSky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnCancel))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        // First we'll check all text fields for valid numbers, and abort if there is a problem
        JTextField[] textFields = { txtYear, txtMonth, txtDay, txtHigh, txtLow };
        for (int i = 0; i < textFields.length; i++) {
            if (validateTextFieldNumber(textFields[i]) == false) {
                return;
            }
        }
        
        // Now, update the day in the logic
        if (dayIndex == -1) {  // if we're adding a new day 
            app.addDay(getTFNum(txtYear), getTFNum(txtMonth), getTFNum(txtDay), getTFNum(txtHigh), getTFNum(txtLow), cmbSky.getSelectedIndex());
        }
        else {
            day.updateDate(getTFNum(txtYear), getTFNum(txtMonth), getTFNum(txtDay));
            day.updateForecast(getTFNum(txtHigh), getTFNum(txtLow), cmbSky.getSelectedIndex());
        }
        
        
        frame.switchToPanel(new AppPanel());
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        frame.switchToPanel(new AppPanel());
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYearFocusLost
        validateTextFieldNumber(txtYear);
    }//GEN-LAST:event_txtYearFocusLost

    private void txtYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYearFocusGained
        txtYear.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtYearFocusGained

    private void txtMonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMonthFocusGained
        txtMonth.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtMonthFocusGained

    private void txtMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMonthFocusLost
        validateTextFieldNumber(txtMonth);
    }//GEN-LAST:event_txtMonthFocusLost

    private void txtDayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDayFocusGained
        txtDay.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtDayFocusGained

    private void txtDayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDayFocusLost
        validateTextFieldNumber(txtDay);
    }//GEN-LAST:event_txtDayFocusLost

    private void txtHighFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHighFocusGained
        txtHigh.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtHighFocusGained

    private void txtHighFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHighFocusLost
        validateTextFieldNumber(txtHigh);
    }//GEN-LAST:event_txtHighFocusLost

    private void txtLowFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLowFocusGained
        txtLow.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtLowFocusGained

    private void txtLowFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLowFocusLost
        validateTextFieldNumber(txtLow);
    }//GEN-LAST:event_txtLowFocusLost

    private boolean validateTextFieldNumber(JTextField tf) {
        try {
            Integer.parseInt(tf.getText());
            return true;
        }
        catch (NumberFormatException e) {
            tf.setBackground(Color.RED);
            return false;
        }
    }
    
    private int getTFNum(JTextField tf) {
        try {
            return Integer.parseInt(tf.getText());
        }
        catch (NumberFormatException e) {
            System.err.println("getTextFieldNumber was called on a text field containing a non-integer");
        }      
        return 0;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSky;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtHigh;
    private javax.swing.JTextField txtLow;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
